import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import { Toaster } from "sonner";

const roboto = Roboto({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        />
      </head>
      <Provider>
        <body className={roboto.className}>
          <NavBar />
          <Toaster
            duration={2000}
            position="top-center"
            richColors
            closeButton
          />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
