import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";

const roboto = Roboto({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={roboto.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
